### ISSUE TITLE
Blog Typos and new post

### ISSUE THREAD

**Issue by theWickedWebDev** [theWickedWebDev/davidadams#22]
Blog entry titles:

"Poor Shadows of Elysium present’s Shakespeare’s Antony & Cleopatra” should read:
Poor Shadows of Elysium presents Shakespeare's Antony & Cleopatra

“Multimedia Collaborated for Ears, Eyes, and Feet” should read:
Multimedia Collaboration for Ears, Eyes, and Feet 

While we’re at it, let’s italicize other titles inside blog entry titles:
Wesley Lunsford – So Much More

Austin Saxophone Ensemble performs American Counterpoint

I’d also like to add a link to the Austin Saxophone Ensemble post:

Whew, what a week! After an excellent concert Sunday by the Austin Saxophone Ensemble (featuring an excellent performance of <a href="https://soundcloud.com/davidcarltonadams/sets/american-counterpoint-austin-sax-ensemble-oct-2014”>American Counterpoint</a> for Sax Quartet by Andy Wilds, Ben Kessler, Charlie Chadwell, and Nathan Mertens!), I had to double-time it writing and rehearsing guitar, piano, and string parts for a new song on an upcoming album, then took off Monday night, studio-bound. Tuesday and Wednesday flew by in the magical blur of recording, and we got some incredible work done. Looking forward now to finishing up the album, and diving back into composition of a more classical-leaning nature!

**Comment by DJOcean** [comment]
I dont understand what im supposed to be italicizing here. is it song titles that appear in other posts? or just song titles in titles?
